id: A3A8DBB65
title: Supplement to the Lineage Prayer for the Lamdré Instructions Composed by Tsarchen
type: translation
pechas:
- I0CE98D90
- I779926BA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:56:20.536980
  last_modified_at: 2023-01-04 11:56:20.536989
  collections:
  - Gatön Ngawang Lekpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I0CE98D90/B3F4: 4B4F
  I779926BA/1341: 4B4F
